
export const TABLE_VIEW = 'TABLE_VIEW';
export const CARDS_VIEW = 'CARDS_VIEW';
export const FAKE_FLASHCARDS_VIEW = "FAKE_FLASHCARDS_VIEW";
export const ARTICLE_VIEW = "ARTICLE_VIEW";
export const SPELLING_TEST = "SPELLING_TEST";
